#pragma once

namespace clickhouse {

enum ErrorCodes {
    CHECKSUM_DOESNT_MATCH = 40,
    CANNOT_PARSE_DATETIME = 41,
    UNKNOWN_FUNCTION = 46,
    UNKNOWN_IDENTIFIER = 47,
    TABLE_ALREADY_EXISTS = 57,
    UNKNOWN_TABLE = 60,
    SYNTAX_ERROR = 62,
    UNKNOWN_DATABASE = 81,
    DATABASE_ALREADY_EXISTS = 82,
    UNKNOWN_PACKET_FROM_CLIENT = 99,
    UNEXPECTED_PACKET_FROM_CLIENT = 101,
    RECEIVED_DATA_FOR_WRONG_QUERY_ID = 103,
    ENGINE_REQUIRED = 119,
    READONLY = 164,
    UNKNOWN_USER = 192,
    WRONG_PASSWORD = 193,
    REQUIRED_PASSWORD = 194,
    IP_ADDRESS_NOT_ALLOWED = 195,
    LIMIT_EXCEEDED = 290,
    UNKNOWN_DATABASE_ENGINE = 336,
    UNKNOWN_EXCEPTION = 1002,
};

}
