#include <clickhouse/base/bignum_string.h>
#include <gtest/gtest.h>
#include "bignum_samples.h"

#include <algorithm>

/**
 * Values for this test can be generated by this python script
 *
```
import sys

def limbs32(value, bits):
    v = int(value) & ((1 << bits) - 1)   # two's-complement to `bits` bits
    mask = (1 << 32) - 1
    # little-endian 32-bit words: words[0] is least significant
    return [(v >> (32 * i)) & mask for i in range(bits // 32)]

if __name__ == "__main__":
    if len(sys.argv) < 4:
        sys.exit("usage: gen_limbs.py <signed|unsigned> <128|256|512> VALUE [VALUE ...]")
    bits = {"128": 128, "256": 256, "512": 512}[sys.argv[2]]
    for value in sys.argv[3:]:
        words = limbs32(value, bits)               # low word first
        lits = ", ".join(f"0x{w:08X}" for w in reversed(words))  # high word first
        print(f'{{"{value}", {{{lits}}}}},')
```
 *
 * Example:
 *     python convert.py signed 128 1 2 5
 *
 * Generates:
 *     {"1", {0x00000000, 0x00000000, 0x00000000, 0x00000001}},
 *     {"2", {0x00000000, 0x00000000, 0x00000000, 0x00000002}},
 *     {"5", {0x00000000, 0x00000000, 0x00000000, 0x00000005}},
 */

using clickhouse::internal::bignum::string::limb_arr_str_len;
using clickhouse::internal::bignum::string::limb_arr_to_str;
using clickhouse::internal::bignum::string::str_to_limb_arr;
using clickhouse::internal::bignum::string::SignMode;
using clickhouse::internal::bignum::string::StatusCode;

#define UINT128_MAX_STR "340282366920938463463374607431768211455"
#define INT128_MAX_STR "170141183460469231731687303715884105727"
#define INT128_MIX_STR "-170141183460469231731687303715884105728"

#define UINT256_MAX_STR "115792089237316195423570985008687907853269984665640564039457584007913129639935"
#define INT256_MAX_STR "57896044618658097711785492504343953926634992332820282019728792003956564819967"
#define INT256_MIX_STR "-57896044618658097711785492504343953926634992332820282019728792003956564819968"

#define UINT512_MAX_STR                                                                                                                    \
    "134078079299425970995740249982058461274793658205923933777235614437217640300735469768018742981669034276900318581864860508537538828119" \
    "46569946433649006084095"
#define INT512_MAX_STR                                                                                                                     \
    "-67039039649712985497870124991029230637396829102961966888617807218608820150367734884009371490834517138450159290932430254268769414059" \
    "73284973216824503042048"
#define INT512_MIX_STR                                                                                                                     \
    "-67039039649712985497870124991029230637396829102961966888617807218608820150367734884009371490834517138450159290932430254268769414059" \
    "73284973216824503042047"

std::string TrimLeadingZeros(const std::string& str) {
    std::string ret{};
    ret.reserve(str.size());

    auto it  = str.cbegin();
    auto end = str.cend();

    if (it < end && *it == '-') {
        ret.push_back('-');
        ++it;
    }

    for (; it < end && *it == '0'; ++it);

    std::copy(it, end, std::back_inserter(ret));

    if (ret.empty() || ret == "-") {
        return "0";
    }
    return ret;
}

// W is the width of the destination integer in 32-bit values
// i.e. 128-bit integer has W=4, 256 - W=8, 512-bit - W=16
template <size_t W>
void CheckToStringSuccess(std::string value, SignMode mode, const std::vector<uint32_t>& expect) {
    SCOPED_TRACE("value = " + value);
    ASSERT_EQ(W, expect.size());
    uint32_t limbs[W] = {0};
    auto res          = str_to_limb_arr(value.c_str(), value.size(), mode, limbs, W);
    EXPECT_EQ(StatusCode::OK, res);

    for (size_t i = 0; i < W; ++i) {
        // `expect` is given in hi-lo order (for readability),
        // but limbs are stored in lo-hi (little-endian)
        EXPECT_EQ(limbs[i], expect[W - i - 1]);
    }

    char buffer[limb_arr_str_len(W)] = {0};
    std::string str_expect           = TrimLeadingZeros(value);
    std::string str                  = limb_arr_to_str(limbs, W, mode, buffer, sizeof(buffer));
    EXPECT_EQ(str, str_expect);
}

template <size_t W>
void CheckToStringBadString(std::string value, SignMode mode) {
    SCOPED_TRACE("value = " + value);
    uint32_t limbs32[W] = {0};
    auto res            = str_to_limb_arr(value.c_str(), value.size(), mode, limbs32, W);
    ASSERT_EQ(StatusCode::BAD_STRING, res);
}

template <size_t W>
void CheckToStringOverflow(std::string value, SignMode mode) {
    SCOPED_TRACE("value = " + value);
    uint32_t limbs32[W] = {0};
    auto res            = str_to_limb_arr(value.c_str(), value.size(), mode, limbs32, W);
    ASSERT_EQ(StatusCode::TOO_LARGE, res);
}

using TestSample = std::pair<std::string, std::vector<uint32_t>>;

TEST(BignumString, UInt128ToString) {
    auto samples = UnsignedInt128Samples();
    for (auto& [value, limbs] : samples) {
        CheckToStringSuccess<4>(value, SignMode::UNSIGNED, limbs);
    }
}

TEST(BignumString, Int128ToString) {
    auto samples = SignedInt128Samples();
    for (auto& [value, limbs] : samples) {
        CheckToStringSuccess<4>(value, SignMode::SIGNED, limbs);
    }
}

TEST(BignumString, Int128Overflow) {
    std::vector<std::string> values = {
        /* ---- SIGNED: positive overflow INT_MAX+1 ( == |INT_MIN| as bare/positive ) ---- */
        "170141183460469231731687303715884105728",
        /* ---- SIGNED: negative overflow INT_MIN-1 ---- */
        "-170141183460469231731687303715884105729",
        /* ---- SIGNED: value far larger than width (positive & negative) ---- */
        "999999999999999999999999999999999999999999999999999999999999",
        "-999999999999999999999999999999999999999999999999999999999999",
        /* ---- SIGNED: unsigned-range value that exceeds signed range ---- */
        "340282366920938463463374607431768211455",
    };

    for (auto& value : values) {
        CheckToStringOverflow<4>(value, SignMode::SIGNED);
    }
}

TEST(BignumString, UInt256ToString) {
    auto samples = UnsignedInt256Samples();
    for (auto& [value, limbs] : samples) {
        CheckToStringSuccess<8>(value, SignMode::UNSIGNED, limbs);
    }
}

TEST(BignumString, Int256ToString) {
    auto samples = SignedInt256Samples();
    for (auto& [value, limbs] : samples) {
        CheckToStringSuccess<8>(value, SignMode::SIGNED, limbs);
    }
}

TEST(BignumString, UInt256Overflow) {
    std::vector<std::string> values = {
        /* UINT_MAX + 1 (same digit length, one greater) */
        "115792089237316195423570985008687907853269984665640564039457584007913129639936",
        /* UINT_MAX + extra digit (one longer) */
        "1157920892373161954235709850086879078532699846656405640394575840079131296399350",
        /* '+'-prefixed overflow (overflow gate must run on signed-number path too) */
        /* value far larger than the width */
        "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    };

    for (auto& value : values) {
        CheckToStringOverflow<8>(value, SignMode::UNSIGNED);
    }
}

TEST(BignumString, Int256Overflow) {
    std::vector<std::string> values = {
        /* INT_MAX + 1 (= 2^255) positive overflow */
        "57896044618658097711785492504343953926634992332820282019728792003956564819968",
        /* '+'-prefixed positive overflow */
        /* sign-asymmetry: "+|INT_MIN|" overflows even though "-|INT_MIN|" is valid */
        "57896044618658097711785492504343953926634992332820282019728792003956564819968",
        /* INT_MIN - 1 (negative overflow) */
        "-57896044618658097711785492504343953926634992332820282019728792003956564819969",
        /* unsigned-max as signed (way past INT_MAX, still within unsigned width) */
        "115792089237316195423570985008687907853269984665640564039457584007913129639935",
        "-115792089237316195423570985008687907853269984665640564039457584007913129639935",
        /* value far larger than the width, both signs */
        "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
        "-999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    };

    for (auto& value : values) {
        CheckToStringOverflow<8>(value, SignMode::SIGNED);
    }
}

TEST(BignumString, UInt512ToString) {
    auto samples = UnsignedInt512Samples();
    for (auto& [value, limbs] : samples) {
        CheckToStringSuccess<16>(value, SignMode::UNSIGNED, limbs);
    }
}

TEST(BignumString, Int512ToString) {
    auto samples = SignedInt512Samples();
    for (auto& [value, limbs] : samples) {
        CheckToStringSuccess<16>(value, SignMode::SIGNED, limbs);
    }
}

TEST(BignumString, UInt512Overflow) {
    std::vector<std::string> values = {
        "134078079299425970995740249982058461274793658205923933777235614437217640300735469768018742"
        "98166903427690031858186486050853753882811946569946433649006084096",
        /* UINT_MAX + extra digit (one longer) */
        "134078079299425970995740249982058461274793658205923933777235614437217640300735469768018742"
        "981669034276900318581864860508537538828119465699464336490060840950",
        /* value far larger than the width */
        "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
        "99999999999999999999999999999999999999999999999999999999999999999999999999",
    };

    for (auto& value : values) {
        CheckToStringOverflow<16>(value, SignMode::UNSIGNED);
    }
}

TEST(BignumString, Int512Overflow) {
    std::vector<std::string> values = {
        /* INT_MAX + 1 (= 2^511, exceeds positive range 2^511-1) */
        // NOLINTNEXTLINE(bugprone-suspicious-missing-comma)
        "6703903964971298549787012499102923063739682910296196688861780721860882015036773488400937149083451713845015929093243025426876941405"
        "973284973216824503042048",
        /* "+|INT_MIN|" => OVERFLOW (positive 2^511 out of range) */
        /* INT_MIN - 1 (negative, beyond -2^511) */
        "-670390396497129854978701249910292306373968291029619668886178072186088201503677348840093714908345171384501592909324302542687694140"
        "5973284973216824503042049",
        /* value far larger than the width, positive and negative */
        "9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
        "9999999999999999999999999999999999",
        "-999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
        "99999999999999999999999999999999999",
        /* unsigned-max magnitude as signed => overflow (UINT_MAX >> INT_MAX, and >> |INT_MIN|) */
        "1340780792994259709957402499820584612747936582059239337772356144372176403007354697680187429816690342769003185818648605085375388281"
        "1946569946433649006084095",
        "-134078079299425970995740249982058461274793658205923933777235614437217640300735469768018742981669034276900318581864860508537538828"
        "11946569946433649006084095",
    };

    for (auto& value : values) {
        CheckToStringOverflow<16>(value, SignMode::SIGNED);
    }
}

TEST(BignumString, BadString) {
    std::vector<std::string> values{
        "",    "+",   "-",    "abc",  "12a3", "0x1f", "12.5", "1e9", "1_000", "1,000", "1/",  "1:", " 12",
        "12 ", "1 2", "\t12", "12\n", "12\r", "12\t", "--1",  "++1", "+-1",   "-+1",   "1-2", "1+", "\xd9\xa2",
    };
    for (auto& value : values) {
        CheckToStringBadString<4>(value, SignMode::UNSIGNED);
        CheckToStringBadString<8>(value, SignMode::UNSIGNED);
        CheckToStringBadString<16>(value, SignMode::UNSIGNED);
        CheckToStringBadString<4>(value, SignMode::SIGNED);
        CheckToStringBadString<8>(value, SignMode::SIGNED);
        CheckToStringBadString<16>(value, SignMode::SIGNED);
    }
}

TEST(BignumString, UnsignedBadString) {
    std::vector<std::string> values = {"-0", "-1", "-10"};
    for (auto& value : values) {
        CheckToStringBadString<4>(value, SignMode::UNSIGNED);
        CheckToStringBadString<8>(value, SignMode::UNSIGNED);
        CheckToStringBadString<16>(value, SignMode::UNSIGNED);
    }
}
