services:
    clickhouse:
        image: 'docker.io/clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-25.12-alpine}'
        container_name: 'clickhouse-odbc-clickhouse-server'
        environment:
            CLICKHOUSE_SKIP_USER_SETUP: 1
        ports:
            - '8123:8123'
            - '9000:9000'
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - './docker-compose/config.xml:/etc/clickhouse-server/config.xml:z'
            - './docker-compose/users.xml:/etc/clickhouse-server/users.xml:z'
        networks:
            - clickhouse-odbc

networks:
    clickhouse-odbc:
        driver: bridge
