name: macOS-ssl
# Almost the same as regular macOS builds, BUT with enabled SSL support, requires OpenSSL installed via Homebrew (openssl@1.1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    uses: ClickHouse/clickhouse-cpp/.github/workflows/macos.yml@master
    with:
      extra_cmake_flags: -DWITH_OPENSSL=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/
      extra_install: openssl
      # There is no CH server running locally, so disable tests that try to connect to it.
      gtest_filter: "-*Client*:*Local*:*ColumnPerformanceTest*"
